### ISSUE TITLE
Why are Site.Params.Author and Site.Author.name separate?

### ISSUE THREAD

**Issue by a-p-o** [EmielH/tale-hugo#36]
I am trying to understand the difference between these fields.

``` toml
# Needed for copyright in footer
[Author]
    name = "Alex Ordonez"

# Needed for "written by" in post-info
[Params]
    Author = "Alex Ordonez"
```

* https://github.com/EmielH/tale-hugo/blob/099821c/layouts/partials/single/post-info.html#L6
* https://github.com/EmielH/tale-hugo/blob/099821c/layouts/partials/footer.html#L3
