### ISSUE TITLE
Code highlighting does not update

### ISSUE THREAD

**Issue by sn0ot** [EmielH/tale-hugo#45]
Changing values in `_syntax.scss` has no effect on the code's syntax highlights.

When building the site, the default style is always "monokai" as mentioned in [Hugo's Configure Markdown Goldmark Highlight](https://gohugo.io/getting-started/configuration-markup#highlight) section. 

The only way I've managed to change theme is by including the following in `config.toml`

```toml
[markup]
    [markup.highlight]
        style = "solarized-dark256"
```

Is there a parameter that needs to be set in `config.toml` to use what is defined in `_syntax.scss`? It is not mentioned in the `README`. sorry for the noob issues :|
